language: python
# cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
# command to install dependencies
install: make requirements && make install
# command to run tests
script: make test
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGlhbmRlbm5pc21pbGxlciUzQW1hdHJpeC5vcmcvJTIxSkRnU2ZuUlpCRktJWmZpSlJlJTNBbWF0cml4Lm9yZw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
