language: python
# cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
# command to install dependencies
install: make requirements install
# command to run tests
script:
  - /bin/bash .travis/test-skel-travis.sh
